#!/usr/bin/env bash

MODULE_NAME="nvim"

MODULE_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
STOW_DIR="$(dirname "$MODULE_DIR")"

pushd $STOW_DIR
stow -t $HOME -D "$MODULE_NAME"
popd

pushd $MODULE_DIR
git submodule deinit --all
popd
